{
 "title": "Smart Data Center Maintenance",
 "time": { "from": "2022-07-15T11:59:56.087Z", "to": "2022-07-15T23:59:56.087Z" },
 "panels": [
  { "title": "Smart Health Bands", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Smart Health Bands Alert Status",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT idband,\n  alertOn\nFROM band_device\n"
    }
   ]
  },
  {
   "title": "Smart Health Bands Active Status",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT idband,\n  alertOn\nFROM band_device\n"
    }
   ]
  },
  { "title": "Environment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Oxygen",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  value AS \"oxygen level\"\nFROM oxygen_samples\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  value AS \"temperature level\"\nFROM temperature_samples\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  value AS \"humidity level\"\nFROM humidity_samples\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  }
 ]
}